# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17d9fa24bf35a288e829d573c7a2eeae03b8bfbe97b7ffab0e6132abb994388b61040c21228c7b2f85a37e7abd48c4aa3479aae7eae1b21b4d805b1517391e8c

test:
  secret_key_base: e676309aed8f2ad48477aa61f052b7cfe6a0b4b23f24cb9493bfbf89fd86cbc655c5726772ab347a0943df320136e6508007bc1aa84b2974023507c9fa442deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
